blog/urls.py
from django.urls import path
from .views import PostsViews, PostDetailView
app_name = 'blog'


urlpatterns = [
    path('', PostsViews, name='posts'),
    path('<id>/', PostDetailView, name='postdetails' ),

]

blog_api/urls.py
from django.urls import path
from .views import PostList, PostDetail

app_name = 'blog_api'

urlpatterns = [
    path('<int:pk>/', PostDetail.as_view(), name='detailcreate'),
    path('', PostList.as_view(), name='listcreate'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('projects/', include('portfolio.urls', namespace='projects')),
    path('api/', include('blog_api.urls', namespace='blog_api')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from .views import homepage,faqs, contact, Portfolio,about, services

app_name = 'home_page'

urlpatterns = [
    path('', homepage, name='homepage'),
    path('faqs/', faqs, name='faqs'),
    path('contact/', contact, name='contact'),
    path('portfolio/', Portfolio, name='portfolio'),
    path('about/', about, name='about'),
    path('services/', services, name='services'),
]

portfolio/urls.py
from django.urls import path
from django.views.generic import TemplateView
from .views import PortfolioViews, PorfolioDetailView
app_name = 'portfolio'

urlpatterns = [
    path('', PortfolioViews, name='projects'),
    path('<id>/', PorfolioDetailView, name='projectdetails' ),

]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from ckeditor.fields import RichTextField


class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Post(models.Model):

    class PostObjects(models.Manager):
        def get_queryset(self):
            return super().get_queryset() .filter(status='published')

    options = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    category = models.ForeignKey(
        Category, on_delete=models.PROTECT, default=1)
    coverimage = models.ImageField(upload_to = 'uploads/',blank=True, null=True)
    projectdetailimage = models.ImageField(upload_to = 'uploads/',blank=True, null=True)
    title = models.CharField(max_length=250)
    excerpt = models.TextField(null=True)
    content = RichTextField()
    slug = models.SlugField(max_length=250, unique_for_date='published')
    published = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='blog_posts')
    status = models.CharField(
        max_length=10, choices=options, default='published')
    objects = models.Manager()  # default manager
    postobjects = PostObjects()  # custom manager

    class Meta:
        ordering = ('-published',)

    def __str__(self):
        return self.title

blog_api/models.py
from django.db import models

pages/models.py
from django.db import models

# Create your models here.

portfolio/models.py
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.
class Portfolio(models.Model):
    coverimage = models.ImageField(upload_to = 'uploads/',blank=True, null=True)
    projectdetailimage = models.ImageField(upload_to = 'uploads/',blank=True, null=True)
    title  = models.CharField(max_length=250)
    date = models.DateField()
    services = models.CharField(max_length=255)
    client = models.CharField(max_length=255)
    location = models.CharField(max_length=255)
    details = RichTextField()

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import get_object_or_404, redirect, render
from .models import Post


def PostsViews(request):
    context ={}
 
    # add the dictionary during initialization
    posts = Post.objects.all()
    context ={
        'posts':posts,
        'page_title':'blog',
    }
    return render(request, 'pages/posts/index.html', context)



def PostDetailView(request, id):
    context ={}
 
    # add the dictionary during initialization
    context["data"] = Post.objects.get(id = id)
         
    return render(request, "pages/posts/post_detail_view.html", context)

blog_api/views.py
from rest_framework import generics
from blog.models import Post
from .serializers import PostSerializer


class PostList(generics.ListCreateAPIView):
    queryset = Post.objects.all()
    serializer_class = PostSerializer


class PostDetail(generics.RetrieveDestroyAPIView):
    queryset = Post.objects.all()
    serializer_class = PostSerializer


""" Concrete View Classes
#CreateAPIView
Used for create-only endpoints.
#ListAPIView
Used for read-only endpoints to represent a collection of model instances.
#RetrieveAPIView
Used for read-only endpoints to represent a single model instance.
#DestroyAPIView
Used for delete-only endpoints for a single model instance.
#UpdateAPIView
Used for update-only endpoints for a single model instance.
##ListCreateAPIView
Used for read-write endpoints to represent a collection of model instances.
RetrieveUpdateAPIView
Used for read or update endpoints to represent a single model instance.
#RetrieveDestroyAPIView
Used for read or delete endpoints to represent a single model instance.
#RetrieveUpdateDestroyAPIView
Used for read-write-delete endpoints to represent a single model instance.
"""

pages/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.core.mail import send_mail

from portfolio.models import Portfolio
from blog.models import Post
# Create your views here.
def homepage(request):
    context ={}
    posts = Post.objects.all()[:3]
    context ={
        'posts':posts,
    }
    return render(request,"pages/home.html", context)

# Faqs

def faqs(request):
    context = {}
    return render(request, 'pages/faqs.html', context)
# contact

def contact(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        email = request.POST.get('email')
        phone = request.POST.get('phone')
        message = request.POST.get('message')
        form_data = {
            'name':name,
            'email':email,
            'phone':phone,
            'message':message,
        }
        message = '''
        From:\n\t\t{}\n
        Message:\n\t\t{}\n
        Email:\n\t\t{}\n
        Phone:\n\t\t{}\n
        '''.format(form_data['name'], form_data['message'], form_data['email'],form_data['phone'])
        send_mail('mail from agency', message, '', ['nisozagency@gmail.com']) # TODO: enter your email address
        return redirect('homepage')
    context = {
        'page_title':'contact us',
    }
    return render(request, 'pages/contact.html', context)
# recent work

def services(request):
    context = {
        'page_title':'our services',
    }
    return render(request, 'pages/services.html', context)
# about

def about(request):
    return render(request, 'pages/about.html')

# meet our team 
def Portfolio(request):
    return render(request, 'pages/portfolio.html')


def PortfolioDetailViews(request, id):
    project = Portfolio.objects.get(id = id)

    return render(request, 'pages/portfolio_detail.html')
# what we offer
# latest news blog

portfolio/views.py
from django.shortcuts import get_object_or_404, redirect, render
from .models import Portfolio


def PortfolioViews(request):
    context ={}
 
    # add the dictionary during initialization
    projects = Portfolio.objects.all()
    context ={
        'projects':projects,
        'page_title':'our projects',
    }
    return render(request, 'pages/portfolio.html', context)


def PorfolioDetailView(request, id):
    context ={}
 
    # add the dictionary during initialization
    context["data"] = Portfolio.objects.get(id = id)
         
    return render(request, "pages/porfolio_detail_view.html", context)

templates/blog/index.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>Document</title>
</head>
<body>
    <h1>blog page</h1>
</body>
</html>

templates/pages/about.html
{% extends "pages/master_page.html" %} 
{% load static %}
{% block title %}  about page  {% endblock %} 


{% block content %}
{% endblock %}

templates/pages/base/blog_section.html
 {% load static %}
<!-- Blog Start -->
        <section class="blog-one">
            <div class="container">
                <div class="row">
                    <div class="col-md-12 wow fadeInUp" data-wow-delay="100ms">
                        <div class="section-title text-center">
                            <div class="section-title__triangle">
                                <span class="section-title__triangle-left"></span>
                                <span class="section-title__triangle-right"></span>
                            </div>
                            <h5 class="section-title__tagline">From the 2 Blog</h5>
                            <h2 class="section-title__title">News & articles</h2>
                        </div><!-- section-title -->
                    </div>
                </div>
                <div class="row">

                {% for post in posts %}
                
                
                    <div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="200ms">
                        <div class="blog-one__item">
                            <div class="blog-one__image">
                                <img src="{% static 'assets/images/blog/blog-1-1.jpg' %} " alt="Five ways that can develop your business">
                                <a href="blog-details-right.html"></a>
                                <div class="blog-one__date">
                                    <span>{{post.published|date:"j"}}</span>
                                    {{post.published|date:"N-Y"}}
                                </div><!-- /.blog-date -->
                            </div><!-- /.blog-image -->
                            <div class="blog-one__content">
                                <div class="blog-one__meta">
                                    <div class="blog-one__meta__author">
                                        <div class="blog-one__meta__thumb"><img src="{{post.coverimage.url}}" alt="{{post.title}}"/></div>
                                        by<br><a href="{% url "blog:postdetails" post.id %}">Layerdrops</a>
                                    </div>
                                    <span class="fas fa-comments"></span>2 Comments
                                </div><!-- /.blog-meta -->
                                <h3 class="blog-one__title">
                                    <a href="{% url "blog:postdetails" post.id %}">{{ post.title }} </a>
                                </h3><!-- /.blog-title -->
                                <a href="{% url "blog:postdetails" post.id %}" class="nisoz-btn">
                                    <span class="nisoz-btn__shape"></span><span class="nisoz-btn__shape"></span><span class="nisoz-btn__shape"></span><span class="nisoz-btn__shape"></span>
                                    <span class="nisoz-btn__text">Read More<span class="icon-right-arrow"></span></span>
                                </a><!-- /.blog-read-more -->
                            </div><!-- /.blog-content -->
                        </div><!-- /.blog-card-one -->
                    </div>
                {% endfor %}  
                    
                </div>
            </div>
        </section>
        <!-- Blog End -->

templates/pages/base/footer.html
 {% load static %}
 <footer class="main-footer">
            <div class="main-footer__bg" style="background-image: url(assets/images/shapes/footer-bg-1.png);"></div>
            <div class="container">
                <div class="main-footer__top wow fadeInUp" data-wow-delay="100ms">
                    <a href="index.html" class="main-footer__logo">
                        <img src="{% static 'assets/images/footer-logo.png' %} " alt="nisoz" width="96" height="34">
                    </a><!-- /.footer-logo -->
                    <div class="main-footer__social">
                        <a href="https://twitter.com/"><i class="fab fa-twitter"></i></a>
                        <a href="https://www.facebook.com/"><i class="fab fa-facebook"></i></a>
                        <a href="https://www.pinterest.com/"><i class="fab fa-pinterest-p"></i></a>
                        <a href="https://www.instagram.com/"><i class="fab fa-instagram"></i></a>
                    </div><!-- /.footer-social -->
                </div><!-- footer-top -->
                <div class="row">
                    <div class="col-lg-2 col-md-4 wow fadeInUp" data-wow-delay="200ms">
                        <div class="main-footer__navmenu">
                            <ul>
                                <li><a href="{% url 'home_page:about' %}">About</a></li>
                                <li><a href="team.html">Meet Our Team</a></li>
                                <li><a href="{% url 'home_page:services' %}">What We Offer</a></li>
                                <li><a href="{% url 'blog:posts' %}">Latest News</a></li>
                            </ul><!-- /.list-unstyled -->
                        </div><!-- /.footer-menu -->
                    </div>
                    <div class="col-lg-2 col-md-4 wow fadeInUp" data-wow-delay="300ms">
                        <div class="main-footer__navmenu">
                            <ul>
                                <li><a href="{% url 'home_page:faqs' %}">Faqs</a></li>
                                <li><a href="{% url 'home_page:contact' %}">Contact</a></li>
                                <li><a href="{% url 'home_page:portfolio' %}">Recent Work</a></li>
                            </ul><!-- /.list-unstyled -->
                        </div><!-- /.footer-menu -->
                    </div>
                    <div class="col-lg-3 col-md-4 wow fadeInUp" data-wow-delay="400ms">
                        <div class="main-footer__about">
                            <p class="main-footer__about__text">36 broklyn golden street. New<br> York. USA</p>
                            <ul class="main-footer__about__info">
                                <li><span class="fas fa-phone-square"></span><a href="tel:+923680006800">+92 (3680) 00 - 6800</a></li>
                                <li><span class="fas fa-envelope"></span><a href="mailto:needhelp@company.com">needhelp@company.com</a></li>
                            </ul>
                        </div><!-- /.footer-about -->
                    </div>
                    <div class="col-lg-5 col-md-12 wow fadeInUp" data-wow-delay="500ms">
                        <div class="main-footer__newsletter">
                            <h5 class="main-footer__newsletter__text">Subscribe to get latest updates on daily basis</h5>
                            <form class="main-footer__email-box mc-form" data-url="MC_FORM_URL" novalidate="novalidate">
                                <div class="main-footer__email-input-box">
                                    <input type="email" placeholder="Email address" name="EMAIL">
                                </div>
                                <button type="submit" class="nisoz-btn">
                                    <span class="nisoz-btn__shape"></span><span class="nisoz-btn__shape"></span><span class="nisoz-btn__shape"></span><span class="nisoz-btn__shape"></span>
                                    <span class="nisoz-btn__text">Subscribe</span>
                                </button>
                            </form>
                            <div class="mc-form__response"></div>
                        </div><!-- /.footer-mailchimp -->
                    </div>
                </div><!-- /.row -->
            </div><!-- /.container -->
        </footer><!-- /.main-footer -->

templates/pages/faqs.html
{% extends "pages/master_page.html" %} 
{% load static %}
{% block title %} our services  {% endblock %} 



{% block content %}


{% endblock %}

templates/pages/home.html
{% extends "pages/master.html" %} 
{% block title %} My Tennis Club - List of all
members {% endblock %} 


{% block content %}

{% endblock %}

templates/pages/master_page.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>{% block title %}{% endblock %}</title>

    <!-- fonts -->
    <link rel="preconnect" href="../../fonts.googleapis.com/index.html" />
    <link
      rel="preconnect"
      href="../../fonts.gstatic.com/index.html"
      crossorigin
    />
    <link
      href="../../fonts.googleapis.com/css282ed.css?family=Barlow+Condensed:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,300;1,400;1,500;1,600;1,700;1,800;1,900&amp;family=Manrope:wght@300;400;500;600;700;800&amp;display=swap"
      rel="stylesheet"
    />

    <link
      rel="stylesheet"
      href="{% static 'assets/vendors/bootstrap/css/bootstrap.min.css' %}"
    />
    <link
      rel="stylesheet"
      href="{% static 'assets/vendors/bootstrap-select/bootstrap-select.min.css' %}"
    />
    <link
      rel="stylesheet"
      href="{% static 'assets/vendors/jquery-ui/jquery-ui.css' %}"
    />
    <link
      rel="stylesheet"
      href="{% static 'assets/vendors/animate/animate.min.css' %}"
    />
    <link
      rel="stylesheet"
      href="{% static 'assets/vendors/fontawesome/css/all.min.css' %}"
    />
    <link
      rel="stylesheet"
      href="{% static 'assets/vendors/nisoz-icons/style.css' %}"
    />
    <link
      rel="stylesheet"
      href="{% static 'assets/vendors/jarallax/jarallax.css' %}"
    />
    <link
      rel="stylesheet"
      href="{% static 'assets/vendors/jquery-magnific-popup/jquery.magnific-popup.css' %}"
    />
    <link
      rel="stylesheet"
      href="{% static 'assets/vendors/nouislider/nouislider.min.css' %}"
    />
    <link
      rel="stylesheet"
      href="{% static 'assets/vendors/nouislider/nouislider.pips.css' %}"
    />
    <link
      rel="stylesheet"
      href="{% static 'assets/vendors/odometer/odometer.min.css' %}"
    />
    <link
      rel="stylesheet"
      href="{% static 'assets/vendors/tiny-slider/tiny-slider.min.css' %}"
    />
    <link
      rel="stylesheet"
      href="{% static 'assets/vendors/owl-carousel/assets/owl.carousel.min.css' %}"
    />
    <link
      rel="stylesheet"
      href="{% static 'assets/vendors/owl-carousel/assets/owl.theme.default.min.css' %}"
    />

    <!-- template styles -->
    <link rel="stylesheet" href="{% static 'assets/css/nisoz.css' %}" />
  </head>
  <body class="custom-cursor">
    <div class="custom-cursor__cursor"></div>
    <div class="custom-cursor__cursor-two"></div>

    <div class="preloader">
      <div
        class="preloader__image"
        style="background-image: url(assets/images/loader.png)"
      ></div>
    </div>
    <!-- /.preloader -->
    <div class="page-wrapper">
      <section class="topbar">
        <div class="container-fluid">
          <div class="topbar__wrapper">
            <ul class="list-unstyled topbar__list">
              <li>
                <span class="fas fa-envelope"></span>
                <a href="mailto:needhelp@company.com">needhelp@company.com</a>
              </li>
              <li>
                <span class="fas fa-map-marker"></span>
                88 Broklyn Golden Street. New York
              </li>
            </ul>
            <!-- /.icon-box -->
            <ul class="list-unstyled topbar__menu">
              <li><a href="{% url 'home_page:faqs' %}">Help</a></li>
              <li><a href="{% url 'home_page:about' %}">Support</a></li>
              <li><a href="{% url 'home_page:contact' %}">Contact</a></li>
            </ul>
            <!-- /.list-menu -->
            <div class="topbar__social">
              <a href="https://twitter.com/"><i class="fab fa-twitter"></i></a>
              <a href="https://www.facebook.com/"
                ><i class="fab fa-facebook"></i
              ></a>
              <a href="https://www.pinterest.com/"
                ><i class="fab fa-pinterest-p"></i
              ></a>
              <a href="https://www.instagram.com/"
                ><i class="fab fa-instagram"></i
              ></a>
            </div>
            <!-- /.social-links -->
          </div>
        </div>
      </section>
      <!-- /.topbar-header -->
      <header class="main-header">
        <nav class="main-menu">
          <div class="container-fluid">
            <div class="main-menu__logo">
              <a href="{% url 'home_page:homepage' %}">
                <img
                  src="{% static 'assets/images/logo-light.png' %}"
                  width="96"
                  height="34"
                  alt="Ogency"
                />
              </a>
            </div>
            <!-- /.main-menu__logo -->
            <div class="main-menu__nav">
              <ul class="main-menu__list">
                <li class="dropdown megamenu">
                  <a href="{% url 'home_page:homepage' %}">Home</a>
                </li>

                <li>
                  <a href="{% url 'home_page:services' %}">Services</a>
                </li>
                <li>
                  <a href="{% url 'portfolio:projects' %}">Portfolio</a>
                </li>
                <li>
                  <a href="{% url 'blog:posts' %}">Blog</a>
                </li>
                <li>
                  <a href="{% url 'home_page:contact' %}">Contact</a>
                </li>
              </ul>
            </div>
            <!-- /.main-menu__nav -->
            <div class="main-menu__right">
              <a href="#" class="main-menu__toggler mobile-nav__toggler">
                <i class="fa fa-bars"></i> </a
              ><!-- /.mobile menu btn -->
              <a href="tel:+9236809850" class="main-menu__phone">
                <i class="icon-telephone"></i>
                +92 (3680) - 9850 </a
              ><!-- /.phone-number -->
              <a href="#" class="main-menu__search search-toggler">
                <i class="icon-magnifying-glass"></i> </a
              ><!-- /.search btn -->
              
            </div>
            <!-- /.main-menu__right -->
          </div>
          <!-- /.container -->
        </nav>
        <!-- /.main-menu -->
      </header>
      <!-- /.main-header -->

      <div class="stricky-header stricked-menu main-menu">
        <div class="sticky-header__content"></div>
        <!-- /.sticky-header__content -->
      </div>
      <!-- /.stricky-header -->

              <section class="page-header">
            <div class="page-header__bg"></div><!-- /.page-header__bg -->
            <div class="page-header__shape1"></div><!-- /.page-header__shape1 -->
            <div class="page-header__shape2"></div><!-- /.page-header__shape1 -->
            <div class="page-header__shape3 wow slideInRight" data-wow-delay="300ms"></div><!-- /.page-header__shape3 -->
            <div class="container">
                <ul class="page-header__breadcrumb list-unstyled">
                    <li><a href="{% url 'home_page:homepage' %}">Home</a></li>
                    
                </ul><!-- /.page-breadcrumb list-unstyled -->
                <h2 class="page-header__title">{{page_title}}</h2><!-- /.page-title -->
            </div><!-- /.container -->
        </section><!-- /.page-header -->
    
    
    {% block content %}

    
    {% endblock %}
      


      {% include 'pages/base/footer.html' %}
      <section class="copyright text-center">
        <div class="container wow fadeInUp" data-wow-delay="500ms">
          <p class="copyright__text">
            © Copyright <span class="dynamic-year"></span
            ><!-- /.dynamic-year -->
            by <a href="https://themeforest.net/item/nisoz-creative-agency-html-template/46985943">Nisoz Template</a>
          </p>
        </div>
        <!-- /.container -->
      </section>
      <!-- /.copyright -->
    </div>
    <!-- /.page-wrapper -->

    <div class="mobile-nav__wrapper">
      <div class="mobile-nav__overlay mobile-nav__toggler"></div>
      <!-- /.mobile-nav__overlay -->
      <div class="mobile-nav__content">
        <span class="mobile-nav__close mobile-nav__toggler"
          ><i class="fa fa-times"></i
        ></span>
        <div class="logo-box">
          <a href="{% url 'home_page:homepage' %}" aria-label="logo image"
            ><img
              src="assets/images/logo-light.png"
              width="96"
              height="34"
              alt="nisoz"
          /></a>
        </div>
        <!-- /.logo-box -->
        <div class="mobile-nav__container"></div>
        <!-- /.mobile-nav__container -->
        <ul class="mobile-nav__contact list-unstyled">
          <li>
            <i class="fas fa-envelope"></i>
            <a href="mailto:needhelp@company.com">needhelp@company.com</a>
          </li>
          <li>
            <i class="fa fa-phone-alt"></i>
            <a href="tel:+9236809850">+92 (3680) - 9850</a>
          </li>
        </ul>
        <!-- /.mobile-nav__contact -->
        <div class="mobile-nav__social">
          <a href="https://twitter.com/"><i class="fab fa-twitter"></i></a>
          <a href="https://www.facebook.com/"
            ><i class="fab fa-facebook"></i
          ></a>
          <a href="https://www.pinterest.com/"
            ><i class="fab fa-pinterest-p"></i
          ></a>
          <a href="https://www.instagram.com/"
            ><i class="fab fa-instagram"></i
          ></a>
        </div>
        <!-- /.mobile-nav__social -->
      </div>
      <!-- /.mobile-nav__content -->
    </div>
    <!-- /.mobile-nav__wrapper -->

    <div class="search-popup">
      <div class="search-popup__overlay search-toggler"></div>
      <!-- /.search-popup__overlay -->
      <div class="search-popup__content">
        <form role="search" method="get" class="search-popup__form" action="#">
          <input type="text" id="search" placeholder="Search Here..." />
          <button type="submit" aria-label="search submit" class="nisoz-btn">
            <span class="nisoz-btn__shape"></span
            ><span class="nisoz-btn__shape"></span
            ><span class="nisoz-btn__shape"></span
            ><span class="nisoz-btn__shape"></span>
            <span class="nisoz-btn__text"
              ><i class="icon-magnifying-glass"></i
            ></span>
          </button>
        </form>
      </div>
      <!-- /.search-popup__content -->
    </div>
    <!-- /.search-popup -->

    <!-- back-to-top-start -->
    <a href="#" class="scroll-top">
      <svg
        class="scroll-top__circle"
        width="100%"
        height="100%"
        viewBox="-1 -1 102 102"
      >
        <path d="M50,1 a49,49 0 0,1 0,98 a49,49 0 0,1 0,-98" />
      </svg>
    </a>
    <!-- back-to-top-end -->

    <script src="{% static 'assets/vendors/jquery/jquery-3.5.1.min.js' %}"></script>
    <script src="{% static 'assets/vendors/bootstrap/js/bootstrap.bundle.min.js' %} "></script>
    <script src="{% static 'assets/vendors/bootstrap-select/bootstrap-select.min.js' %} "></script>
    <script src="{% static 'assets/vendors/jquery-ui/jquery-ui.js' %}"></script>
    <script src="{% static 'assets/vendors/jarallax/jarallax.min.js' %}"></script>
    <script src="{% static 'assets/vendors/jquery-ajaxchimp/jquery.ajaxchimp.min.js' %} "></script>
    <script src="{% static 'assets/vendors/jquery-appear/jquery.appear.min.js' %} "></script>
    <script src="{% static 'assets/vendors/jquery-circle-progress/jquery.circle-progress.min.js' %} "></script>
    <script src="{% static 'assets/vendors/jquery-magnific-popup/jquery.magnific-popup.min.js' %} "></script>
    <script src="{% static 'assets/vendors/jquery-validate/jquery.validate.min.js' %} "></script>
    <script src="{% static 'assets/vendors/nouislider/nouislider.min.js' %} "></script>
    <script src="{% static 'assets/vendors/odometer/odometer.min.js' %} "></script>
    <script src="{% static 'assets/vendors/tiny-slider/tiny-slider.min.js' %} "></script>
    <script src="{% static 'assets/vendors/owl-carousel/owl.carousel.min.js' %} "></script>
    <script src="{% static 'assets/vendors/wnumb/wNumb.min.js' %} "></script>
    <script src="{% static 'assets/vendors/jquery-circleType/jquery.circleType.js' %} "></script>
    <script src="{% static 'assets/vendors/jquery-lettering/jquery.lettering.min.js' %} "></script>
    <script src="{% static 'assets/vendors/tilt/tilt.jquery.js' %} "></script>
    <script src="{% static 'assets/vendors/wow/wow.js' %} "></script>
    <script src="{% static 'assets/vendors/isotope/isotope.js' %} "></script>
    <script src="{% static 'assets/vendors/countdown/countdown.min.js' %} "></script>
    <!-- template js -->
    <script src="{% static 'assets/js/nisoz.js' %} "></script>
  </body>
</html>

templates/pages/portfolio.html
{% extends "pages/master_page.html" %} 
{% load static %}
{% block title %} our services  {% endblock %} 



{% block content %}

        <!-- Portfolio Start -->
        <section class="portfolio-one portfolio-page">
            <div class="container">
                <div class="row nisoz-masonary">
                    {% for data in projects %}.
                    <div class="col-lg-4 col-md-6">
                        <div class="portfolio-one__item">
                            <div class="portfolio-one__thumb">
                                <img src=" {{data.coverimage.url}}" alt="nisoz" />
                            </div>
                            <div class="portfolio-one__hover">
                                <a class="portfolio-one__read-more" href="{% url "portfolio:projectdetails" data.id %}"><span class="icon-right-arrow"></span></a>
                                <div class="portfolio-one__hover-bottom">
                                    
                                    <h3 class="portfolio-one__title"><a href="{% url "portfolio:projectdetails" data.id %}">{{ data.title }}</a></h3>
                                </div>
                            </div>
                        </div><!-- folio-item -->
                    </div>

                    {% endfor %}
                   
                </div><!-- slider-end -->
            </div>
        </section>
        <!-- Portfolio End -->

{% endblock %}